In [1]:
# Pandas and NumPy
import pandas as pd
import numpy as np

In [2]:
#[flights] dataset_01 => all "Active Regular Flights" from 2017, from january to september
#source: http://www.anac.gov.br/assuntos/dados-e-estatisticas/historico-de-voos
#Last access this website: nov, 14th, 2017
flights = pd.read_csv('data/arf2017.csv', sep = ';', parse_dates = True)

In [3]:
flights.head(10)

,airline,flightcode,authcode,linecode,airportA,airportB,departureest,departurereal,arrivalest,arrivalreal,flightstatus,problemcode
0,AAL,213,0,I,KMIA,SBBR,02/01/2017 01:20,02/01/2017 01:20,02/01/2017 09:00,02/01/2017 09:00,REALIZADO,NaN
1,AAL,213,0,I,KMIA,SBBR,24/01/2017 01:20,24/01/2017 01:20,24/01/2017 09:00,24/01/2017 09:00,REALIZADO,NaN
2,AAL,213,0,I,KMIA,SBBR,29/01/2017 01:20,29/01/2017 01:20,29/01/2017 09:00,29/01/2017 09:00,REALIZADO,NaN
3,AAL,213,0,I,KMIA,SBBR,23/01/2017 01:20,23/01/2017 01:20,23/01/2017 09:00,23/01/2017 09:00,REALIZADO,NaN
4,AAL,213,0,I,KMIA,SBBR,25/01/2017 01:20,25/01/2017 01:20,25/01/2017 09:00,25/01/2017 09:00,REALIZADO,NaN
5,AAL,213,0,I,KMIA,SBBR,08/01/2017 01:20,08/01/2017 01:20,08/01/2017 09:00,08/01/2017 09:00,REALIZADO,NaN
6,AAL,213,0,I,KMIA,SBBR,13/01/2017 01:20,13/01/2017 01:20,13/01/2017 09:00,13/01/2017 09:00,REALIZADO,NaN
7,AAL,213,0,I,KMIA,SBBR,20/01/2017 01:20,20/01/2017 01:20,20/01/2017 09:00,20/01/2017 09:00,REALIZADO,NaN
8,AAL,213,0,I,KMIA,SBBR,11/01/2017 01:20,11/01/2017 01:20,11/01/2017 09:00,11/01/2017 09:00,REALIZADO,NaN
9,AAL,213,0,I,KMIA,SBBR,09/01/2017 01:20,09/01/2017 02:06,09/01/2017 09:00,09/01/2017 09:22,REALIZADO,TD

In [7]:
#[airports] dataset_02 => all public brazilian airports (last update: oct, 2017)
#source: http://www.anac.gov.br/assuntos/setor-regulado/aerodromos/cadastro-de-aerodromos/aerodromos-cadastrados/aerodromospublicos-12.xls
#Last access this website: nov, 14th, 2017
airports = pd.read_csv('data/brazilianPublicAirports-out2017.csv', sep = ';')

In [8]:
airports.head(10)

,airport,airportname,city,state,latitude,longitude,altitude,operation
0,SBAA,CONCEIÇÃO DO ARAGUAIA,CONCEIÇÃO DO ARAGUAIA,PA,8° 20' 55'' S,49° 18' 11'' W,199 m,VFR Diurno/Noturno e IFR Diurno
1,SBAE,BAURU/AREALVA,BAURU E AREALVA,SP,22° 9' 28'' S,49° 4' 6'' W,594 m,VFR Diurno/Noturno e IFR Diurno/Noturno
2,SBAM,AMAPÁ,AMAPÁ,AP,2° 4' 22'' N,50° 51' 45'' W,14 m,VFR Diurno e IFR Diurno
3,SBAQ,BARTOLOMEU DE GUSMÃO,ARARAQUARA,SP,21° 48' 16'' S,48° 8' 25'' W,711 m,VFR Diurno/Noturno e IFR Diurno/Noturno
4,SBAR,SANTA MARIA,ARACAJU,SE,10° 59' 7'' S,37° 4' 24'' W,7 m,VFR Diurno/Noturno e IFR Diurno/Noturno
5,SBAT,PILOTO OSVALDO MARQUES DIAS,ALTA FLORESTA,MT,9° 51' 59'' S,56° 6' 18'' W,289 m,VFR Diurno/Noturno e IFR Diurno/Noturno
6,SBAU,ESTADUAL DARIO GUARITA,ARAÇATUBA,SP,21° 8' 39'' S,50° 25' 35'' W,415 m,VFR Diurno/Noturno e IFR Diurno/Noturno
7,SBAX,ROMEU ZEMA,ARAXÁ,MG,19° 33' 38'' S,46° 57' 56'' W,999 m,VFR Diurno/Noturno e IFR Diurno/Noturno
8,SBBE,INTERNACIONAL DE BELÉM/VAL DE CANS/JÚLIO CEZAR...,BELÉM,PA,1° 23' 5'' S,48° 28' 44'' W,17 m,VFR Diurno/Noturno e IFR Diurno/Noturno
9,SBBG,COMANDANTE GUSTAVO KRAEMER,BAGÉ,RS,31° 23' 27'' S,54° 6' 35'' W,183 m,VFR Diurno/Noturno e IFR Diurno/Noturno

In [9]:
airports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 589 entries, 0 to 588
Data columns (total 8 columns):
airport        589 non-null object
airportname    589 non-null object
city           589 non-null object
state          589 non-null object
latitude       589 non-null object
longitude      589 non-null object
altitude       589 non-null object
operation      589 non-null object
dtypes: object(8)
memory usage: 36.9+ KB